### ISSUE TITLE
Crash when using optifabric and pressing f3

### ISSUE THREAD

**Issue by RyanCR03** [joaoh1/BoringTweaks#3]
game crashes with optifabric and boringtweaks and pressing f3
https://pastelink.net/2b8hh

**Comment by ghost** [comment]
Fixed on the next update. Since it caused a crash and OptiFine has heavily modified the debug HUD, I decided to make the mixin fail without failing hard (plus fix compatibility with other mods). However, OptiFabric will not be directly supported due to OptiFine being quite hard to work with
